CFG:
  # dataset args
  task: ner
  dset_name: klue
  PLM: klue/bert-base
  seed: 42
  num_labels: 7

  max_token_length: 120
  train_batch_size: 32
  vaild_batch_size: 32
  num_epochs: 5
  learning_rate: 0.0003
  weight_decay: 0.001
  warmup_ratio: 0.05
  dropout: 0.1
  text_column_name: sentence
  label_column_name: ner_tags
  padding: max_length
  
